### ISSUE TITLE
Problem initializing

### ISSUE THREAD

**Issue by lacoprof** [PHP-DI/ZF1-Bridge#11]
Hi after installing with composer and adding init method to my Bootstrap.php iam getting following error in my webapp :

Fatal error: Uncaught exception 'Zend_Application_Bootstrap_Exception' with message 'No default controller directory registered with front controller'

Any tips? Thanks

**Comment by mnapoli** [comment]
Hi, it seems to me like an error with Zend Framework, not the PHP-DI integration. Have you tried making your application work without PHP-DI first?

**Comment by lacoprof** [comment]
Hi Matthieu, thanks for reply. It legacy app, and works correctly when i not change the standard dispatcher with \DI\Bridge\ZendFramework1\Dispatcher();
The stacktrace points to /Zend/Application/Bootstrap/Bootstrap.php run() method

**Comment by mnapoli** [comment]
Ah ok, I honestly have never seen that error before. I can't really help you much on this since I no longer use ZF1, maybe you could try to debug using xdebug? Also check that you do have a default controller directory? (e.g. http://forums.zend.com/viewtopic.php?f=69&t=6732)

**Comment by lacoprof** [comment]
Thanks for your time, controller directory is set correctly... i have tried the xdebug, i dont know the internals of ZF1, but it looks it makes some additional checks inside of Standard dispatcher with _defaultModule . The app is very basic and uses Zend_Registry as service locator...  i try to find more and i let you know...

**Comment by mnapoli** [comment]
OK, do you have the latest version of ZF1? Maybe there's a difference somewhere :/

**Comment by lacoprof** [comment]
Yes i have tried with latest 1.12.* but the app was designed with 1.10.*

**Comment by lacoprof** [comment]
Hi, i just found some workaround to make it work, the _initContainer() method should also copy the controllerDirectory from old dispatcher instance, before changing to front controller
```php
        $builder = new \DI\ContainerBuilder();
        $container = $builder->build();
        $dispatcher = new \DI\Bridge\ZendFramework1\Dispatcher();
        $dispatcher->setContainer($container);
        $dispatcher_old =  Zend_Controller_Front::getInstance()->getDispatcher();
        $dispatcher->setControllerDirectory( $dispatcher_old->getControllerDirectory());
        Zend_Controller_Front::getInstance()->setDispatcher($dispatcher);
```
