### ISSUE TITLE
Sample code not working

### ISSUE THREAD

**Issue by jstormes** [PHP-DI/ZF1-Bridge#12]
I am sure I am just missing something, I am trying to duplicate the sample code at [http://php-di.org/doc/frameworks/zf1.html](http://php-di.org/doc/frameworks/zf1.html) with a "Hello World" controller.

#Bootstrap.php
```<?php

class Bootstrap extends Zend_Application_Bootstrap_Bootstrap
{
    protected function _initContainer()
    {
        $builder = new \DI\ContainerBuilder();
        $container = $builder->build();
        
    
        $dispatcher = new \DI\Bridge\ZendFramework1\Dispatcher();
        $dispatcher->setContainer($container);
    
        Zend_Controller_Front::getInstance()->setDispatcher($dispatcher);
    }

}
```
#IndexController.php
```<?php

class IndexController extends Zend_Controller_Action
{
    
    /**
     * This dependency will be injected by PHP-DI
     * @Inject
     * @var Application_Model_HelloWorld
     */
    private $hw;

    public function init()
    {
        /* Initialize action controller here */
    }

    public function indexAction()
    {
        // action body
        
        //$this->hw = new Application_Model_HelloWorld();
        
        $this->view->helloworld = $this->hw->Msg();
    }


}
```

#HelloWorld.php
```<?php
class Application_Model_HelloWorld
{
    function __construct() {
        fb("Hello");
    }
    
    public function Msg() {
        return "Hello World";
    }
}
```

The code works fine when I uncomment `$this->hw = new Application_Model_HelloWorld();` but my understanding is that auto-wiring would instantiate the object.  Not sure if my understanding is wrong or my code is wrong.

Any help would be appreciated.

Thanks

**Comment by mnapoli** [comment]
Hi!

My guess is that you are using PHP-DI 5 (which was released a few months ago). With this new version, annotations are disabled by default (see http://php-di.org/doc/annotations.html).

To enable them in your code, change the Bootstrap code:

```php
class Bootstrap extends Zend_Application_Bootstrap_Bootstrap
{
    protected function _initContainer()
    {
        $builder = new \DI\ContainerBuilder();
        // Enable annotations
        $builder->useAnnotations(true);
        $container = $builder->build();

        $dispatcher = new \DI\Bridge\ZendFramework1\Dispatcher();
        $dispatcher->setContainer($container);

        Zend_Controller_Front::getInstance()->setDispatcher($dispatcher);
    }
}
```

**Comment by mnapoli** [comment]
I see that the official documentation is misleading because it doesn't mention it: http://php-di.org/doc/frameworks/zf1.html

I will open an issue in the main repository and close this one. Thanks!

**Comment by mnapoli** [comment]
I've opened https://github.com/PHP-DI/PHP-DI/issues/298.

**Comment by mnapoli** [comment]
Actually I've updated the documentation directly: https://github.com/PHP-DI/PHP-DI/commit/bd8c5f616324ab175ef01151740b7f54fb9c2851

**Comment by jstormes** [comment]
It works, thank you.
