### ISSUE TITLE
The ZF1 bridge requires doctrine annotations?

### ISSUE THREAD

**Issue by domoran** [PHP-DI/ZF1-Bridge#13]
PHP DI does not require doctrine/annotations - when installed it just recommends installing it. But ZF1 seems to require it, therefore it should be added to composer.json.

**Comment by mnapoli** [comment]
It shouldn't require it. Maybe it's just the quickstart that does?

**Comment by amakhrov** [comment]
ZF1 Bridge doesn't require that. However, ZF1 Bridge does rely on [php-di's annotations](http://php-di.org/doc/annotations.html), which in turns rely on doctrine/annotations.

**Comment by mnapoli** [comment]
Except the quickstart the code of this package doesn't require it: https://github.com/PHP-DI/ZF1-Bridge/tree/master/src/DI/Bridge/ZendFramework1 Controllers can be configured using PHP-DI config files.

**Comment by domoran** [comment]
Ok. Maybe add a comment to the quickstart if this is supposed to be a "quick" start. It was not obvious for someone (like me) that didn't know PHP-DI at all before. Because without it you will simply get no injections and therefore not a clear error message that will hint to you what is wrong.

**Comment by mnapoli** [comment]
Good point, I have edited the readme to make it more clear.

Thanks!
