### ISSUE TITLE
Should update to allow version 6

### ISSUE THREAD

**Issue by twisty** [PHP-DI/ZF1-Bridge#16]
https://github.com/PHP-DI/ZF1-Bridge/blob/a0357dcb7ab5be9a0578d49ff95e5f24eec4e920/composer.json#L13

Can the dependency on `~5.0` be amended allow installing version 6? I think `~5.0 || ~6.0` should do it?

At first glance it seems that v6 should be compatible with the dispatcher in this repo? The example app looks to have been kept simple (no caching or complex config) and ought to work with v6 too?

**Comment by mnapoli** [comment]
Agreed, and yes I think this should do it:

> I think `~5.0 || ~6.0` should do it?

Please send a pull request?

**Comment by twisty** [comment]
Here you go: #17

**Comment by mnapoli** [comment]
Thanks I've created a new major release!
