### ISSUE TITLE
Handling not existent controllers/actions

### ISSUE THREAD

**Issue by colorninja** [PHP-DI/ZF1-Bridge#18]
I keep getting 500 errors in an error tracking software because apple devices try to request `apple-touch-icon-precomposed.png`, which we do not have set up and bots constantly trying to access common paths (eg. `/wp-admin/`, `/news`, `/cms`)

This comes down to the controller not existing and therefore the bridge plugin is throwing `Zend_Controller_Dispatcher_Exception`

Is there a way to handle the following exceptions (in `/src/DI/Bridge/ZendFramework1/Dispatcher.php:50`) properly and display a 404 instead of 500:
```
throw new Zend_Controller_Dispatcher_Exception('Invalid controller specified (' . $request->getControllerName() . ')');
```

**Comment by mnapoli** [comment]
Hi!

I'm sorry but I'm not actively maintaining this package as ZF1 has been dead for many years. I spend my "open-source time" on other projects instead.

If you do need professional support I can set aside a few hours/days to help you, please send me an email: matthieu@null.tc

Hope you understand!
